#!/usr/bin/env node
/*!
 * Sketches
 * Copyright(c) 2016-2019 Francesco Bianco
 * MIT Licensed
 */

'use strict';

const sketches = require('path').join(process.cwd(), './node_modules/sketches')
require(require('fs').existsSync(sketches) ? sketches : '.').cli.run(process.argv.slice(2))
